name: chromatic 👓
on: push

jobs:
    run:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1
            - run: |
                  yarn && yarn makeBuild
            - uses: chromaui/action@v1
              with:
                  appCode: ${{ secrets.CHROMATIC_APP_CODE }}
                  token: ${{ secrets.GITHUB_TOKEN }}
